In [1]:
import pandas as pd
import numpy as np
import networkx as nx
from sklearn.cluster import SpectralClustering
from sklearn import metrics
import random

access_token = 'pk.eyJ1IjoiZGFlZG9sIiwiYSI6ImNqZGpqbmpnYzFscm8yd245YXM5MWQxeGgifQ.ACxKlSjUthNpixmVX2faMw'
view_options = {
    'center': [127.021633, 37.248900],
    'zoom': 11,
    'bearing': 0,
    'pitch': 20,
    'style': 'mapbox://styles/mapbox/dark-v9',
    'access_token': access_token
}

ModuleNotFoundError: No module named 'sklearn'

In [4]:
df = pd.read_csv('../data/df_time_int.csv')

FileNotFoundError: [Errno 2] File b'../data/df_time_int.csv' does not exist: b'../data/df_time_int.csv'

In [2]:
df_station = pd.read_csv('../data/PJT001_stations_table.csv')

In [3]:
df = df.iloc[:,1:]

NameError: name 'df' is not defined

In [161]:
df = df + 1e-3

In [162]:
sc = SpectralClustering(4, affinity='precomputed', n_init=100)
sc.fit(df)

# Compare ground-truth and clustering-results
print('spectral clustering')
print(sc.labels_)
print('just for better-visualization: invert clusters (permutation)')
print(np.abs(sc.labels_ - 1))

# Calculate some clustering metrics
#print(metrics.adjusted_rand_score(gt, sc.labels_))
#print(metrics.adjusted_mutual_info_score(gt, sc.labels_))

spectral clustering
[0 0 1 ... 0 0 0]
just for better-visualization: invert clusters (permutation)
[1 1 0 ... 1 1 1]


In [163]:
index = df.columns

In [164]:
index = index.astype(int)

In [165]:
df_index = pd.DataFrame([range(len(df)),index,sc.labels_]).T

In [166]:
df_index.columns = ['index','표준정류장ID','label']

In [167]:
df_ = pd.merge(df_index, 
             df_station[['표준정류장ID','WGS84위도', 'WGS84경도']],
             on='표준정류장ID', how='left')


In [168]:
stations = df_0.iloc[:,3:5]

NameError: name 'df_0' is not defined

In [169]:
data = []

In [170]:
def cluster_visualization(df):
    stations = df.iloc[:,2:5]
    data = []
    print(stations.head())
    colors = [] 
    len_color = len(stations['label'].unique())
    for _ in range(len_color):
        colors.append([random.randrange(0,255),random.randrange(0,255),random.randrange(0,255)])
    for i in range(len(stations)):
        label,lat,lon = stations.iloc[i,:]
        data.append({'coordinates': [lon, lat], 'values':100*(label+1),'color':colors[int(label)]})
    return data

In [171]:
data = cluster_visualization(df_)

   label    WGS84위도     WGS84경도
0      0  37.237717  126.962400
1      0  37.229317  126.970433
2      1  37.101367  126.948400
3      1  37.086417  126.942483
4      0  37.090283  126.941967


In [172]:
import os

from deckgljupyter import Layer
import numpy as np

import warnings
warnings.filterwarnings('ignore')
'''
data = [
    {'coordinates': [126.81561169069604, 37.08218248972286], 'values': 66},
    {'coordinates': [126.82831786376109, 37.08140909828359], 'values': 23},
    {'coordinates': [126.8387065894608, 37.06699779260753], 'values': 58},
    {'coordinates': [126.84606088258417, 37.06672832706917], 'values': 39},
    {'coordinates': [126.84662056554762, 37.037944216429445], 'values': 95},
    {'coordinates': [126.8440176576777, 37.037963591237336], 'values': 5},
    {'coordinates': [126.84591452407986, 37.066818241654104], 'values': 6},
    {'coordinates': [126.83047144100027, 37.07895232384016], 'values': 39},
    {'coordinates': [126.81582783195088, 37.082250988510175], 'values': 26}
]

'''
m = Layer.Map(**view_options)
GC_layer = Layer.GridCellLayer(data,
                               cellSize=200,
                               getPosition='obj => obj.coordinates',getElevation=70,
                               getColor='obj => obj.color')

m.add(GC_layer)
m.show()

일반화 시키고 조금 보인다 싶으면 GCN-edge로 한번 돌려보기


In [147]:
df_user = pd.read_csv('../data/df_bus_user.csv')

In [148]:
df_user = df_user.iloc[:,1:]

In [149]:
sc_user = SpectralClustering(5, affinity='precomputed', n_init=100)
sc_user.fit(df_user)

# Compare ground-truth and clustering-results
print('spectral clustering')
print(sc_user.labels_)
print('just for better-visualization: invert clusters (permutation)')
print(np.abs(sc_user.labels_ - 1))

# Calculate some clustering metrics
#print(metrics.adjusted_rand_score(gt, sc.labels_))
#print(metrics.adjusted_mutual_info_score(gt, sc.labels_))

spectral clustering
[2 2 2 ... 2 2 2]
just for better-visualization: invert clusters (permutation)
[1 1 1 ... 1 1 1]


In [150]:
df_user_index = pd.DataFrame([range(len(df_user)),index,sc.labels_]).T

In [151]:
df_user_index.columns = ['index','표준정류장ID','label']

In [152]:
df_user = pd.merge(df_user_index, 
             df_station[['표준정류장ID','WGS84위도', 'WGS84경도']],
             on='표준정류장ID', how='left')


In [155]:
data_user = cluster_visualization(df_user)

   label    WGS84위도     WGS84경도
0      0  37.237717  126.962400
1      0  37.229317  126.970433
2      3  37.101367  126.948400
3      3  37.086417  126.942483
4      0  37.090283  126.941967


In [156]:
import os

from deckgljupyter import Layer
import numpy as np

import warnings
warnings.filterwarnings('ignore')
'''
data = [
    {'coordinates': [126.81561169069604, 37.08218248972286], 'values': 66},
    {'coordinates': [126.82831786376109, 37.08140909828359], 'values': 23},
    {'coordinates': [126.8387065894608, 37.06699779260753], 'values': 58},
    {'coordinates': [126.84606088258417, 37.06672832706917], 'values': 39},
    {'coordinates': [126.84662056554762, 37.037944216429445], 'values': 95},
    {'coordinates': [126.8440176576777, 37.037963591237336], 'values': 5},
    {'coordinates': [126.84591452407986, 37.066818241654104], 'values': 6},
    {'coordinates': [126.83047144100027, 37.07895232384016], 'values': 39},
    {'coordinates': [126.81582783195088, 37.082250988510175], 'values': 26}
]

'''
m = Layer.Map(**view_options)
GC_layer = Layer.GridCellLayer(data_user,
                               cellSize=200,
                               getPosition='obj => obj.coordinates',getElevation=70,
                               getColor='obj => obj.color')

m.add(GC_layer)
m.show()

In [195]:
def visualize(file='df_bus_user.csv',n_cluster=10):
    df_user = pd.read_csv('../data/'+file)
    df_user = df_user.iloc[:,1:]
    sc_user = SpectralClustering(n_cluster, affinity='precomputed', n_init=100)
    sc_user.fit(df_user)
    # Compare ground-truth and clustering-results
    print('spectral clustering')
    print(sc_user.labels_)
    print('just for better-visualization: invert clusters (permutation)')
    #print(np.abs(sc_user.labels_ - 1))

    # Calculate some clustering metrics
    #print(metrics.adjusted_rand_score(gt, sc.labels_))
    #print(metrics.adjusted_mutual_info_score(gt, sc.labels_))
    df_user_index = pd.DataFrame([range(len(df_user)),index,sc.labels_]).T
    df_user_index.columns = ['index','표준정류장ID','label']
    df_user = pd.merge(df_user_index, 
                 df_station[['표준정류장ID','WGS84위도', 'WGS84경도']],
                 on='표준정류장ID', how='left')
    data_user = cluster_visualization(df_user)
    import os

    from deckgljupyter import Layer
    import numpy as np

    import warnings
    warnings.filterwarnings('ignore')
    '''
    data = [
        {'coordinates': [126.81561169069604, 37.08218248972286], 'values': 66},
        {'coordinates': [126.82831786376109, 37.08140909828359], 'values': 23},
        {'coordinates': [126.8387065894608, 37.06699779260753], 'values': 58},
        {'coordinates': [126.84606088258417, 37.06672832706917], 'values': 39},
        {'coordinates': [126.84662056554762, 37.037944216429445], 'values': 95},
        {'coordinates': [126.8440176576777, 37.037963591237336], 'values': 5},
        {'coordinates': [126.84591452407986, 37.066818241654104], 'values': 6},
        {'coordinates': [126.83047144100027, 37.07895232384016], 'values': 39},
        {'coordinates': [126.81582783195088, 37.082250988510175], 'values': 26}
    ]

    '''
    m = Layer.Map(**view_options)
    GC_layer = Layer.GridCellLayer(data_user,
                                   cellSize=200,
                                   getPosition='obj => obj.coordinates',getElevation=70,
                                   getColor='obj => obj.color')

    m.add(GC_layer)
    m.show()

In [196]:
visualize('df_bus_user.csv',10)

spectral clustering
[0 0 0 ... 0 0 0]
just for better-visualization: invert clusters (permutation)
   label    WGS84위도     WGS84경도
0      0  37.237717  126.962400
1      0  37.229317  126.970433
2      1  37.101367  126.948400
3      1  37.086417  126.942483
4      0  37.090283  126.941967


In [ ]:
feature에 위도 경도를 넣어본다.
승하차 수도 넣어본다.

그리고 efficiency 같은 걸로 edge를 만들어서
graph clustering을 해본다.
